 platform :ios, '8.0'

target 'SampleApp' do
  use_frameworks!

# IF USING REMOTE PATH, RUN SAMPLE APP TO SEE BUILD ERROR.
# SAMPLE APP RUNS SUCCESSFULLY WHEN POD INSTALLING USING LOCAL PATH.

  pod 'SDKWithVungle/Vungle', :git => 'git@github.com:bryanboyko/PodFrameworkWithVungleDependency'
#  pod 'SDKWithVungle/Vungle', :path => "../.."

  target 'SampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SampleAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
